/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthenticationSession model module.
 * @module model/AuthenticationSession
 * @version latest
 */
class AuthenticationSession {
    /**
     * Constructs a new <code>AuthenticationSession</code>.
     * AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession AuthenticationSession authentication session
     * @alias module:model/AuthenticationSession
     */
    constructor() { 
        
        AuthenticationSession.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthenticationSession</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthenticationSession} obj Optional instance to populate.
     * @return {module:model/AuthenticationSession} The populated <code>AuthenticationSession</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticationSession();

            if (data.hasOwnProperty('AuthenticatedAt')) {
                obj['AuthenticatedAt'] = ApiClient.convertToType(data['AuthenticatedAt'], 'Date');
            }
            if (data.hasOwnProperty('ID')) {
                obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
            }
            if (data.hasOwnProperty('Subject')) {
                obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
            }
        }
        return obj;
    }


}

/**
 * authenticated at Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time Format: date-time
 * @member {Date} AuthenticatedAt
 */
AuthenticationSession.prototype['AuthenticatedAt'] = undefined;

/**
 * ID
 * @member {String} ID
 */
AuthenticationSession.prototype['ID'] = undefined;

/**
 * subject
 * @member {String} Subject
 */
AuthenticationSession.prototype['Subject'] = undefined;






export default AuthenticationSession;

