/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Client from './Client';
import OpenIDConnectContext from './OpenIDConnectContext';

/**
 * The AuthenticationRequest model module.
 * @module model/AuthenticationRequest
 * @version latest
 */
class AuthenticationRequest {
    /**
     * Constructs a new <code>AuthenticationRequest</code>.
     * @alias module:model/AuthenticationRequest
     */
    constructor() { 
        
        AuthenticationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthenticationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthenticationRequest} obj Optional instance to populate.
     * @return {module:model/AuthenticationRequest} The populated <code>AuthenticationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticationRequest();

            if (data.hasOwnProperty('challenge')) {
                obj['challenge'] = ApiClient.convertToType(data['challenge'], 'String');
            }
            if (data.hasOwnProperty('client')) {
                obj['client'] = Client.constructFromObject(data['client']);
            }
            if (data.hasOwnProperty('oidc_context')) {
                obj['oidc_context'] = OpenIDConnectContext.constructFromObject(data['oidc_context']);
            }
            if (data.hasOwnProperty('request_url')) {
                obj['request_url'] = ApiClient.convertToType(data['request_url'], 'String');
            }
            if (data.hasOwnProperty('requested_access_token_audience')) {
                obj['requested_access_token_audience'] = ApiClient.convertToType(data['requested_access_token_audience'], ['String']);
            }
            if (data.hasOwnProperty('requested_scope')) {
                obj['requested_scope'] = ApiClient.convertToType(data['requested_scope'], ['String']);
            }
            if (data.hasOwnProperty('session_id')) {
                obj['session_id'] = ApiClient.convertToType(data['session_id'], 'String');
            }
            if (data.hasOwnProperty('skip')) {
                obj['skip'] = ApiClient.convertToType(data['skip'], 'Boolean');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Challenge is the identifier (\"authentication challenge\") of the consent authentication request. It is used to identify the session.
 * @member {String} challenge
 */
AuthenticationRequest.prototype['challenge'] = undefined;

/**
 * @member {module:model/Client} client
 */
AuthenticationRequest.prototype['client'] = undefined;

/**
 * @member {module:model/OpenIDConnectContext} oidc_context
 */
AuthenticationRequest.prototype['oidc_context'] = undefined;

/**
 * RequestURL is the original OAuth 2.0 Authorization URL requested by the OAuth 2.0 client. It is the URL which initiates the OAuth 2.0 Authorization Code or OAuth 2.0 Implicit flow. This URL is typically not needed, but might come in handy if you want to deal with additional request parameters.
 * @member {String} request_url
 */
AuthenticationRequest.prototype['request_url'] = undefined;

/**
 * RequestedScope contains the access token audience as requested by the OAuth 2.0 Client.
 * @member {Array.<String>} requested_access_token_audience
 */
AuthenticationRequest.prototype['requested_access_token_audience'] = undefined;

/**
 * RequestedScope contains the OAuth 2.0 Scope requested by the OAuth 2.0 Client.
 * @member {Array.<String>} requested_scope
 */
AuthenticationRequest.prototype['requested_scope'] = undefined;

/**
 * SessionID is the authentication session ID. It is set if the browser had a valid authentication session at ORY Hydra during the login flow. It can be used to associate consecutive login requests by a certain user.
 * @member {String} session_id
 */
AuthenticationRequest.prototype['session_id'] = undefined;

/**
 * Skip, if true, implies that the client has requested the same scopes from the same user previously. If true, you can skip asking the user to grant the requested scopes, and simply forward the user to the redirect URL.  This feature allows you to update / set session information.
 * @member {Boolean} skip
 */
AuthenticationRequest.prototype['skip'] = undefined;

/**
 * Subject is the user ID of the end-user that authenticated. Now, that end user needs to grant or deny the scope requested by the OAuth 2.0 client. If this value is set and `skip` is true, you MUST include this subject type when accepting the login request, or the request will fail.
 * @member {String} subject
 */
AuthenticationRequest.prototype['subject'] = undefined;






export default AuthenticationRequest;

