/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompletedRequest model module.
 * @module model/CompletedRequest
 * @version latest
 */
class CompletedRequest {
    /**
     * Constructs a new <code>CompletedRequest</code>.
     * @alias module:model/CompletedRequest
     */
    constructor() { 
        
        CompletedRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompletedRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompletedRequest} obj Optional instance to populate.
     * @return {module:model/CompletedRequest} The populated <code>CompletedRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompletedRequest();

            if (data.hasOwnProperty('redirect_to')) {
                obj['redirect_to'] = ApiClient.convertToType(data['redirect_to'], 'String');
            }
        }
        return obj;
    }


}

/**
 * RedirectURL is the URL which you should redirect the user to once the authentication process is completed.
 * @member {String} redirect_to
 */
CompletedRequest.prototype['redirect_to'] = undefined;






export default CompletedRequest;

