/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JSONWebKey from './JSONWebKey';

/**
 * The JSONWebKeySet model module.
 * @module model/JSONWebKeySet
 * @version latest
 */
class JSONWebKeySet {
    /**
     * Constructs a new <code>JSONWebKeySet</code>.
     * @alias module:model/JSONWebKeySet
     */
    constructor() { 
        
        JSONWebKeySet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JSONWebKeySet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JSONWebKeySet} obj Optional instance to populate.
     * @return {module:model/JSONWebKeySet} The populated <code>JSONWebKeySet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JSONWebKeySet();

            if (data.hasOwnProperty('keys')) {
                obj['keys'] = ApiClient.convertToType(data['keys'], [JSONWebKey]);
            }
        }
        return obj;
    }


}

/**
 * The value of the \"keys\" parameter is an array of JWK values.  By default, the order of the JWK values within the array does not imply an order of preference among them, although applications of JWK Sets can choose to assign a meaning to the order for their purposes, if desired.
 * @member {Array.<module:model/JSONWebKey>} keys
 */
JSONWebKeySet.prototype['keys'] = undefined;






export default JSONWebKeySet;

