/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RejectRequest model module.
 * @module model/RejectRequest
 * @version latest
 */
class RejectRequest {
    /**
     * Constructs a new <code>RejectRequest</code>.
     * @alias module:model/RejectRequest
     */
    constructor() { 
        
        RejectRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RejectRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RejectRequest} obj Optional instance to populate.
     * @return {module:model/RejectRequest} The populated <code>RejectRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RejectRequest();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('error_debug')) {
                obj['error_debug'] = ApiClient.convertToType(data['error_debug'], 'String');
            }
            if (data.hasOwnProperty('error_description')) {
                obj['error_description'] = ApiClient.convertToType(data['error_description'], 'String');
            }
            if (data.hasOwnProperty('error_hint')) {
                obj['error_hint'] = ApiClient.convertToType(data['error_hint'], 'String');
            }
            if (data.hasOwnProperty('status_code')) {
                obj['status_code'] = ApiClient.convertToType(data['status_code'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} error
 */
RejectRequest.prototype['error'] = undefined;

/**
 * @member {String} error_debug
 */
RejectRequest.prototype['error_debug'] = undefined;

/**
 * @member {String} error_description
 */
RejectRequest.prototype['error_description'] = undefined;

/**
 * @member {String} error_hint
 */
RejectRequest.prototype['error_hint'] = undefined;

/**
 * @member {Number} status_code
 */
RejectRequest.prototype['status_code'] = undefined;






export default RejectRequest;

