/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RequestDeniedError model module.
 * @module model/RequestDeniedError
 * @version latest
 */
class RequestDeniedError {
    /**
     * Constructs a new <code>RequestDeniedError</code>.
     * @alias module:model/RequestDeniedError
     */
    constructor() { 
        
        RequestDeniedError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequestDeniedError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestDeniedError} obj Optional instance to populate.
     * @return {module:model/RequestDeniedError} The populated <code>RequestDeniedError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestDeniedError();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('error_debug')) {
                obj['error_debug'] = ApiClient.convertToType(data['error_debug'], 'String');
            }
            if (data.hasOwnProperty('error_description')) {
                obj['error_description'] = ApiClient.convertToType(data['error_description'], 'String');
            }
            if (data.hasOwnProperty('error_hint')) {
                obj['error_hint'] = ApiClient.convertToType(data['error_hint'], 'String');
            }
            if (data.hasOwnProperty('status_code')) {
                obj['status_code'] = ApiClient.convertToType(data['status_code'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * name
 * @member {String} error
 */
RequestDeniedError.prototype['error'] = undefined;

/**
 * debug
 * @member {String} error_debug
 */
RequestDeniedError.prototype['error_debug'] = undefined;

/**
 * description
 * @member {String} error_description
 */
RequestDeniedError.prototype['error_description'] = undefined;

/**
 * hint
 * @member {String} error_hint
 */
RequestDeniedError.prototype['error_hint'] = undefined;

/**
 * code
 * @member {Number} status_code
 */
RequestDeniedError.prototype['status_code'] = undefined;






export default RequestDeniedError;

