/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SwaggerNotReadyStatus model module.
 * @module model/SwaggerNotReadyStatus
 * @version latest
 */
class SwaggerNotReadyStatus {
    /**
     * Constructs a new <code>SwaggerNotReadyStatus</code>.
     * SwaggerNotReadyStatus swagger not ready status
     * @alias module:model/SwaggerNotReadyStatus
     */
    constructor() { 
        
        SwaggerNotReadyStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SwaggerNotReadyStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwaggerNotReadyStatus} obj Optional instance to populate.
     * @return {module:model/SwaggerNotReadyStatus} The populated <code>SwaggerNotReadyStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerNotReadyStatus();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * Errors contains a list of errors that caused the not ready status.
 * @member {Object.<String, String>} errors
 */
SwaggerNotReadyStatus.prototype['errors'] = undefined;






export default SwaggerNotReadyStatus;

