/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FlushInactiveOAuth2TokensRequest from './FlushInactiveOAuth2TokensRequest';

/**
 * The SwaggerFlushInactiveAccessTokens model module.
 * @module model/SwaggerFlushInactiveAccessTokens
 * @version latest
 */
class SwaggerFlushInactiveAccessTokens {
    /**
     * Constructs a new <code>SwaggerFlushInactiveAccessTokens</code>.
     * @alias module:model/SwaggerFlushInactiveAccessTokens
     */
    constructor() { 
        
        SwaggerFlushInactiveAccessTokens.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SwaggerFlushInactiveAccessTokens</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwaggerFlushInactiveAccessTokens} obj Optional instance to populate.
     * @return {module:model/SwaggerFlushInactiveAccessTokens} The populated <code>SwaggerFlushInactiveAccessTokens</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerFlushInactiveAccessTokens();

            if (data.hasOwnProperty('Body')) {
                obj['Body'] = FlushInactiveOAuth2TokensRequest.constructFromObject(data['Body']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/FlushInactiveOAuth2TokensRequest} Body
 */
SwaggerFlushInactiveAccessTokens.prototype['Body'] = undefined;






export default SwaggerFlushInactiveAccessTokens;

