/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JSONWebKeySet from './JSONWebKeySet';

/**
 * The SwaggerJwkUpdateSet model module.
 * @module model/SwaggerJwkUpdateSet
 * @version latest
 */
class SwaggerJwkUpdateSet {
    /**
     * Constructs a new <code>SwaggerJwkUpdateSet</code>.
     * @alias module:model/SwaggerJwkUpdateSet
     * @param set {String} The set in: path
     */
    constructor(set) { 
        
        SwaggerJwkUpdateSet.initialize(this, set);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, set) { 
        obj['set'] = set;
    }

    /**
     * Constructs a <code>SwaggerJwkUpdateSet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwaggerJwkUpdateSet} obj Optional instance to populate.
     * @return {module:model/SwaggerJwkUpdateSet} The populated <code>SwaggerJwkUpdateSet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerJwkUpdateSet();

            if (data.hasOwnProperty('Body')) {
                obj['Body'] = JSONWebKeySet.constructFromObject(data['Body']);
            }
            if (data.hasOwnProperty('set')) {
                obj['set'] = ApiClient.convertToType(data['set'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/JSONWebKeySet} Body
 */
SwaggerJwkUpdateSet.prototype['Body'] = undefined;

/**
 * The set in: path
 * @member {String} set
 */
SwaggerJwkUpdateSet.prototype['set'] = undefined;






export default SwaggerJwkUpdateSet;

