/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Swaggeroauth2TokenResponse model module.
 * @module model/Swaggeroauth2TokenResponse
 * @version latest
 */
class Swaggeroauth2TokenResponse {
    /**
     * Constructs a new <code>Swaggeroauth2TokenResponse</code>.
     * Swaggeroauth2TokenResponse The Access Token Response
     * @alias module:model/Swaggeroauth2TokenResponse
     */
    constructor() { 
        
        Swaggeroauth2TokenResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Swaggeroauth2TokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Swaggeroauth2TokenResponse} obj Optional instance to populate.
     * @return {module:model/Swaggeroauth2TokenResponse} The populated <code>Swaggeroauth2TokenResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Swaggeroauth2TokenResponse();

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('redirect_uri')) {
                obj['redirect_uri'] = ApiClient.convertToType(data['redirect_uri'], 'String');
            }
        }
        return obj;
    }


}

/**
 * access token
 * @member {String} access_token
 */
Swaggeroauth2TokenResponse.prototype['access_token'] = undefined;

/**
 * refresh token
 * @member {String} client_id
 */
Swaggeroauth2TokenResponse.prototype['client_id'] = undefined;

/**
 * token type
 * @member {String} code
 */
Swaggeroauth2TokenResponse.prototype['code'] = undefined;

/**
 * expires in
 * @member {String} redirect_uri
 */
Swaggeroauth2TokenResponse.prototype['redirect_uri'] = undefined;






export default Swaggeroauth2TokenResponse;

