/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SwaggerOAuthIntrospectionRequest model module.
 * @module model/SwaggerOAuthIntrospectionRequest
 * @version latest
 */
class SwaggerOAuthIntrospectionRequest {
    /**
     * Constructs a new <code>SwaggerOAuthIntrospectionRequest</code>.
     * @alias module:model/SwaggerOAuthIntrospectionRequest
     * @param token {String} The string value of the token. For access tokens, this is the \"access_token\" value returned from the token endpoint defined in OAuth 2.0. For refresh tokens, this is the \"refresh_token\" value returned.
     */
    constructor(token) { 
        
        SwaggerOAuthIntrospectionRequest.initialize(this, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token) { 
        obj['token'] = token;
    }

    /**
     * Constructs a <code>SwaggerOAuthIntrospectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwaggerOAuthIntrospectionRequest} obj Optional instance to populate.
     * @return {module:model/SwaggerOAuthIntrospectionRequest} The populated <code>SwaggerOAuthIntrospectionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerOAuthIntrospectionRequest();

            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An optional, space separated list of required scopes. If the access token was not granted one of the scopes, the result of active will be false.  in: formData
 * @member {String} scope
 */
SwaggerOAuthIntrospectionRequest.prototype['scope'] = undefined;

/**
 * The string value of the token. For access tokens, this is the \"access_token\" value returned from the token endpoint defined in OAuth 2.0. For refresh tokens, this is the \"refresh_token\" value returned.
 * @member {String} token
 */
SwaggerOAuthIntrospectionRequest.prototype['token'] = undefined;






export default SwaggerOAuthIntrospectionRequest;

