/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SwaggerRevokeOAuth2TokenParameters model module.
 * @module model/SwaggerRevokeOAuth2TokenParameters
 * @version latest
 */
class SwaggerRevokeOAuth2TokenParameters {
    /**
     * Constructs a new <code>SwaggerRevokeOAuth2TokenParameters</code>.
     * @alias module:model/SwaggerRevokeOAuth2TokenParameters
     * @param token {String} in: formData
     */
    constructor(token) { 
        
        SwaggerRevokeOAuth2TokenParameters.initialize(this, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token) { 
        obj['token'] = token;
    }

    /**
     * Constructs a <code>SwaggerRevokeOAuth2TokenParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwaggerRevokeOAuth2TokenParameters} obj Optional instance to populate.
     * @return {module:model/SwaggerRevokeOAuth2TokenParameters} The populated <code>SwaggerRevokeOAuth2TokenParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerRevokeOAuth2TokenParameters();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * in: formData
 * @member {String} token
 */
SwaggerRevokeOAuth2TokenParameters.prototype['token'] = undefined;






export default SwaggerRevokeOAuth2TokenParameters;

