/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SwaggerHealthStatus model module.
 * @module model/SwaggerHealthStatus
 * @version latest
 */
class SwaggerHealthStatus {
    /**
     * Constructs a new <code>SwaggerHealthStatus</code>.
     * SwaggerHealthStatus swagger health status
     * @alias module:model/SwaggerHealthStatus
     */
    constructor() { 
        
        SwaggerHealthStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SwaggerHealthStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwaggerHealthStatus} obj Optional instance to populate.
     * @return {module:model/SwaggerHealthStatus} The populated <code>SwaggerHealthStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerHealthStatus();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Status always contains \"ok\".
 * @member {String} status
 */
SwaggerHealthStatus.prototype['status'] = undefined;






export default SwaggerHealthStatus;

