/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Swaggeroauth2TokenParameters model module.
 * @module model/Swaggeroauth2TokenParameters
 * @version latest
 */
class Swaggeroauth2TokenParameters {
    /**
     * Constructs a new <code>Swaggeroauth2TokenParameters</code>.
     * @alias module:model/Swaggeroauth2TokenParameters
     * @param grantType {String} in: formData
     */
    constructor(grantType) { 
        
        Swaggeroauth2TokenParameters.initialize(this, grantType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, grantType) { 
        obj['grant_type'] = grantType;
    }

    /**
     * Constructs a <code>Swaggeroauth2TokenParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Swaggeroauth2TokenParameters} obj Optional instance to populate.
     * @return {module:model/Swaggeroauth2TokenParameters} The populated <code>Swaggeroauth2TokenParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Swaggeroauth2TokenParameters();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('grant_type')) {
                obj['grant_type'] = ApiClient.convertToType(data['grant_type'], 'String');
            }
            if (data.hasOwnProperty('redirect_uri')) {
                obj['redirect_uri'] = ApiClient.convertToType(data['redirect_uri'], 'String');
            }
        }
        return obj;
    }


}

/**
 * in: formData
 * @member {String} client_id
 */
Swaggeroauth2TokenParameters.prototype['client_id'] = undefined;

/**
 * in: formData
 * @member {String} code
 */
Swaggeroauth2TokenParameters.prototype['code'] = undefined;

/**
 * in: formData
 * @member {String} grant_type
 */
Swaggeroauth2TokenParameters.prototype['grant_type'] = undefined;

/**
 * in: formData
 * @member {String} redirect_uri
 */
Swaggeroauth2TokenParameters.prototype['redirect_uri'] = undefined;






export default Swaggeroauth2TokenParameters;

