/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OryHydra);
  }
}(this, function(expect, OryHydra) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OryHydra.ConsentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ConsentRequest', function() {
    it('should create an instance of ConsentRequest', function() {
      // uncomment below and update the code to test ConsentRequest
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be.a(OryHydra.ConsentRequest);
    });

    it('should have the property acr (base name: "acr")', function() {
      // uncomment below and update the code to test the property acr
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property challenge (base name: "challenge")', function() {
      // uncomment below and update the code to test the property challenge
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property client (base name: "client")', function() {
      // uncomment below and update the code to test the property client
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property context (base name: "context")', function() {
      // uncomment below and update the code to test the property context
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property loginChallenge (base name: "login_challenge")', function() {
      // uncomment below and update the code to test the property loginChallenge
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property loginSessionId (base name: "login_session_id")', function() {
      // uncomment below and update the code to test the property loginSessionId
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property oidcContext (base name: "oidc_context")', function() {
      // uncomment below and update the code to test the property oidcContext
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property requestUrl (base name: "request_url")', function() {
      // uncomment below and update the code to test the property requestUrl
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property requestedAccessTokenAudience (base name: "requested_access_token_audience")', function() {
      // uncomment below and update the code to test the property requestedAccessTokenAudience
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property requestedScope (base name: "requested_scope")', function() {
      // uncomment below and update the code to test the property requestedScope
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property skip (base name: "skip")', function() {
      // uncomment below and update the code to test the property skip
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instane = new OryHydra.ConsentRequest();
      //expect(instance).to.be();
    });

  });

}));
