/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OryHydra);
  }
}(this, function(expect, OryHydra) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OryHydra.WellKnown();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WellKnown', function() {
    it('should create an instance of WellKnown', function() {
      // uncomment below and update the code to test WellKnown
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be.a(OryHydra.WellKnown);
    });

    it('should have the property authorizationEndpoint (base name: "authorization_endpoint")', function() {
      // uncomment below and update the code to test the property authorizationEndpoint
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property backchannelLogoutSessionSupported (base name: "backchannel_logout_session_supported")', function() {
      // uncomment below and update the code to test the property backchannelLogoutSessionSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property backchannelLogoutSupported (base name: "backchannel_logout_supported")', function() {
      // uncomment below and update the code to test the property backchannelLogoutSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property claimsParameterSupported (base name: "claims_parameter_supported")', function() {
      // uncomment below and update the code to test the property claimsParameterSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property claimsSupported (base name: "claims_supported")', function() {
      // uncomment below and update the code to test the property claimsSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property endSessionEndpoint (base name: "end_session_endpoint")', function() {
      // uncomment below and update the code to test the property endSessionEndpoint
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property frontchannelLogoutSessionSupported (base name: "frontchannel_logout_session_supported")', function() {
      // uncomment below and update the code to test the property frontchannelLogoutSessionSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property frontchannelLogoutSupported (base name: "frontchannel_logout_supported")', function() {
      // uncomment below and update the code to test the property frontchannelLogoutSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property grantTypesSupported (base name: "grant_types_supported")', function() {
      // uncomment below and update the code to test the property grantTypesSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property idTokenSigningAlgValuesSupported (base name: "id_token_signing_alg_values_supported")', function() {
      // uncomment below and update the code to test the property idTokenSigningAlgValuesSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property issuer (base name: "issuer")', function() {
      // uncomment below and update the code to test the property issuer
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property jwksUri (base name: "jwks_uri")', function() {
      // uncomment below and update the code to test the property jwksUri
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property registrationEndpoint (base name: "registration_endpoint")', function() {
      // uncomment below and update the code to test the property registrationEndpoint
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property requestParameterSupported (base name: "request_parameter_supported")', function() {
      // uncomment below and update the code to test the property requestParameterSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property requestUriParameterSupported (base name: "request_uri_parameter_supported")', function() {
      // uncomment below and update the code to test the property requestUriParameterSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property requireRequestUriRegistration (base name: "require_request_uri_registration")', function() {
      // uncomment below and update the code to test the property requireRequestUriRegistration
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property responseModesSupported (base name: "response_modes_supported")', function() {
      // uncomment below and update the code to test the property responseModesSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property responseTypesSupported (base name: "response_types_supported")', function() {
      // uncomment below and update the code to test the property responseTypesSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property revocationEndpoint (base name: "revocation_endpoint")', function() {
      // uncomment below and update the code to test the property revocationEndpoint
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property scopesSupported (base name: "scopes_supported")', function() {
      // uncomment below and update the code to test the property scopesSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property subjectTypesSupported (base name: "subject_types_supported")', function() {
      // uncomment below and update the code to test the property subjectTypesSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property tokenEndpoint (base name: "token_endpoint")', function() {
      // uncomment below and update the code to test the property tokenEndpoint
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property tokenEndpointAuthMethodsSupported (base name: "token_endpoint_auth_methods_supported")', function() {
      // uncomment below and update the code to test the property tokenEndpointAuthMethodsSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property userinfoEndpoint (base name: "userinfo_endpoint")', function() {
      // uncomment below and update the code to test the property userinfoEndpoint
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

    it('should have the property userinfoSigningAlgValuesSupported (base name: "userinfo_signing_alg_values_supported")', function() {
      // uncomment below and update the code to test the property userinfoSigningAlgValuesSupported
      //var instane = new OryHydra.WellKnown();
      //expect(instance).to.be();
    });

  });

}));
