/**
 * ORY Hydra
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AcceptConsentRequest from './model/AcceptConsentRequest';
import AcceptLoginRequest from './model/AcceptLoginRequest';
import AuthenticationRequest from './model/AuthenticationRequest';
import AuthenticationSession from './model/AuthenticationSession';
import Client from './model/Client';
import CompletedRequest from './model/CompletedRequest';
import ConsentRequest from './model/ConsentRequest';
import ConsentRequestSession from './model/ConsentRequestSession';
import ConsentRequestSessionData from './model/ConsentRequestSessionData';
import CreateRequest from './model/CreateRequest';
import FlushInactiveOAuth2TokensRequest from './model/FlushInactiveOAuth2TokensRequest';
import GenericError from './model/GenericError';
import HandledConsentRequest from './model/HandledConsentRequest';
import HandledLoginRequest from './model/HandledLoginRequest';
import HealthNotReadyStatus from './model/HealthNotReadyStatus';
import HealthStatus from './model/HealthStatus';
import Introspection from './model/Introspection';
import JSONWebKey from './model/JSONWebKey';
import JSONWebKeySet from './model/JSONWebKeySet';
import JsonWebKeySetGeneratorRequest from './model/JsonWebKeySetGeneratorRequest';
import LoginRequest from './model/LoginRequest';
import OAuth2Client from './model/OAuth2Client';
import OAuth2TokenIntrospection from './model/OAuth2TokenIntrospection';
import Oauth2TokenResponse from './model/Oauth2TokenResponse';
import OauthTokenResponse from './model/OauthTokenResponse';
import OpenIDConnectContext from './model/OpenIDConnectContext';
import PreviousConsentSession from './model/PreviousConsentSession';
import RejectRequest from './model/RejectRequest';
import RequestDeniedError from './model/RequestDeniedError';
import RequestHandlerResponse from './model/RequestHandlerResponse';
import SwaggerFlushInactiveAccessTokens from './model/SwaggerFlushInactiveAccessTokens';
import SwaggerHealthStatus from './model/SwaggerHealthStatus';
import SwaggerJSONWebKey from './model/SwaggerJSONWebKey';
import SwaggerJSONWebKeyQuery from './model/SwaggerJSONWebKeyQuery';
import SwaggerJSONWebKeySet from './model/SwaggerJSONWebKeySet';
import SwaggerJsonWebKeyQuery from './model/SwaggerJsonWebKeyQuery';
import SwaggerJwkCreateSet from './model/SwaggerJwkCreateSet';
import SwaggerJwkSetQuery from './model/SwaggerJwkSetQuery';
import SwaggerJwkUpdateSet from './model/SwaggerJwkUpdateSet';
import SwaggerJwkUpdateSetKey from './model/SwaggerJwkUpdateSetKey';
import SwaggerNotReadyStatus from './model/SwaggerNotReadyStatus';
import SwaggerOAuthIntrospectionRequest from './model/SwaggerOAuthIntrospectionRequest';
import SwaggerOAuthTokenResponse from './model/SwaggerOAuthTokenResponse';
import SwaggerRevokeOAuth2TokenParameters from './model/SwaggerRevokeOAuth2TokenParameters';
import SwaggerVersion from './model/SwaggerVersion';
import Swaggeroauth2TokenParameters from './model/Swaggeroauth2TokenParameters';
import Swaggeroauth2TokenResponse from './model/Swaggeroauth2TokenResponse';
import SwaggeruserinfoResponsePayload from './model/SwaggeruserinfoResponsePayload';
import UserinfoResponse from './model/UserinfoResponse';
import Version from './model/Version';
import WellKnown from './model/WellKnown';
import AdminApi from './api/AdminApi';
import HealthApi from './api/HealthApi';
import PublicApi from './api/PublicApi';
import VersionApi from './api/VersionApi';


/**
* Welcome_to_the_ORY_Hydra_HTTP_API_documentation__You_will_find_documentation_for_all_HTTP_APIs_here_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OryHydra = require('index'); // See note below*.
* var xxxSvc = new OryHydra.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OryHydra.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OryHydra.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OryHydra.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version latest
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AcceptConsentRequest model constructor.
     * @property {module:model/AcceptConsentRequest}
     */
    AcceptConsentRequest,

    /**
     * The AcceptLoginRequest model constructor.
     * @property {module:model/AcceptLoginRequest}
     */
    AcceptLoginRequest,

    /**
     * The AuthenticationRequest model constructor.
     * @property {module:model/AuthenticationRequest}
     */
    AuthenticationRequest,

    /**
     * The AuthenticationSession model constructor.
     * @property {module:model/AuthenticationSession}
     */
    AuthenticationSession,

    /**
     * The Client model constructor.
     * @property {module:model/Client}
     */
    Client,

    /**
     * The CompletedRequest model constructor.
     * @property {module:model/CompletedRequest}
     */
    CompletedRequest,

    /**
     * The ConsentRequest model constructor.
     * @property {module:model/ConsentRequest}
     */
    ConsentRequest,

    /**
     * The ConsentRequestSession model constructor.
     * @property {module:model/ConsentRequestSession}
     */
    ConsentRequestSession,

    /**
     * The ConsentRequestSessionData model constructor.
     * @property {module:model/ConsentRequestSessionData}
     */
    ConsentRequestSessionData,

    /**
     * The CreateRequest model constructor.
     * @property {module:model/CreateRequest}
     */
    CreateRequest,

    /**
     * The FlushInactiveOAuth2TokensRequest model constructor.
     * @property {module:model/FlushInactiveOAuth2TokensRequest}
     */
    FlushInactiveOAuth2TokensRequest,

    /**
     * The GenericError model constructor.
     * @property {module:model/GenericError}
     */
    GenericError,

    /**
     * The HandledConsentRequest model constructor.
     * @property {module:model/HandledConsentRequest}
     */
    HandledConsentRequest,

    /**
     * The HandledLoginRequest model constructor.
     * @property {module:model/HandledLoginRequest}
     */
    HandledLoginRequest,

    /**
     * The HealthNotReadyStatus model constructor.
     * @property {module:model/HealthNotReadyStatus}
     */
    HealthNotReadyStatus,

    /**
     * The HealthStatus model constructor.
     * @property {module:model/HealthStatus}
     */
    HealthStatus,

    /**
     * The Introspection model constructor.
     * @property {module:model/Introspection}
     */
    Introspection,

    /**
     * The JSONWebKey model constructor.
     * @property {module:model/JSONWebKey}
     */
    JSONWebKey,

    /**
     * The JSONWebKeySet model constructor.
     * @property {module:model/JSONWebKeySet}
     */
    JSONWebKeySet,

    /**
     * The JsonWebKeySetGeneratorRequest model constructor.
     * @property {module:model/JsonWebKeySetGeneratorRequest}
     */
    JsonWebKeySetGeneratorRequest,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The OAuth2Client model constructor.
     * @property {module:model/OAuth2Client}
     */
    OAuth2Client,

    /**
     * The OAuth2TokenIntrospection model constructor.
     * @property {module:model/OAuth2TokenIntrospection}
     */
    OAuth2TokenIntrospection,

    /**
     * The Oauth2TokenResponse model constructor.
     * @property {module:model/Oauth2TokenResponse}
     */
    Oauth2TokenResponse,

    /**
     * The OauthTokenResponse model constructor.
     * @property {module:model/OauthTokenResponse}
     */
    OauthTokenResponse,

    /**
     * The OpenIDConnectContext model constructor.
     * @property {module:model/OpenIDConnectContext}
     */
    OpenIDConnectContext,

    /**
     * The PreviousConsentSession model constructor.
     * @property {module:model/PreviousConsentSession}
     */
    PreviousConsentSession,

    /**
     * The RejectRequest model constructor.
     * @property {module:model/RejectRequest}
     */
    RejectRequest,

    /**
     * The RequestDeniedError model constructor.
     * @property {module:model/RequestDeniedError}
     */
    RequestDeniedError,

    /**
     * The RequestHandlerResponse model constructor.
     * @property {module:model/RequestHandlerResponse}
     */
    RequestHandlerResponse,

    /**
     * The SwaggerFlushInactiveAccessTokens model constructor.
     * @property {module:model/SwaggerFlushInactiveAccessTokens}
     */
    SwaggerFlushInactiveAccessTokens,

    /**
     * The SwaggerHealthStatus model constructor.
     * @property {module:model/SwaggerHealthStatus}
     */
    SwaggerHealthStatus,

    /**
     * The SwaggerJSONWebKey model constructor.
     * @property {module:model/SwaggerJSONWebKey}
     */
    SwaggerJSONWebKey,

    /**
     * The SwaggerJSONWebKeyQuery model constructor.
     * @property {module:model/SwaggerJSONWebKeyQuery}
     */
    SwaggerJSONWebKeyQuery,

    /**
     * The SwaggerJSONWebKeySet model constructor.
     * @property {module:model/SwaggerJSONWebKeySet}
     */
    SwaggerJSONWebKeySet,

    /**
     * The SwaggerJsonWebKeyQuery model constructor.
     * @property {module:model/SwaggerJsonWebKeyQuery}
     */
    SwaggerJsonWebKeyQuery,

    /**
     * The SwaggerJwkCreateSet model constructor.
     * @property {module:model/SwaggerJwkCreateSet}
     */
    SwaggerJwkCreateSet,

    /**
     * The SwaggerJwkSetQuery model constructor.
     * @property {module:model/SwaggerJwkSetQuery}
     */
    SwaggerJwkSetQuery,

    /**
     * The SwaggerJwkUpdateSet model constructor.
     * @property {module:model/SwaggerJwkUpdateSet}
     */
    SwaggerJwkUpdateSet,

    /**
     * The SwaggerJwkUpdateSetKey model constructor.
     * @property {module:model/SwaggerJwkUpdateSetKey}
     */
    SwaggerJwkUpdateSetKey,

    /**
     * The SwaggerNotReadyStatus model constructor.
     * @property {module:model/SwaggerNotReadyStatus}
     */
    SwaggerNotReadyStatus,

    /**
     * The SwaggerOAuthIntrospectionRequest model constructor.
     * @property {module:model/SwaggerOAuthIntrospectionRequest}
     */
    SwaggerOAuthIntrospectionRequest,

    /**
     * The SwaggerOAuthTokenResponse model constructor.
     * @property {module:model/SwaggerOAuthTokenResponse}
     */
    SwaggerOAuthTokenResponse,

    /**
     * The SwaggerRevokeOAuth2TokenParameters model constructor.
     * @property {module:model/SwaggerRevokeOAuth2TokenParameters}
     */
    SwaggerRevokeOAuth2TokenParameters,

    /**
     * The SwaggerVersion model constructor.
     * @property {module:model/SwaggerVersion}
     */
    SwaggerVersion,

    /**
     * The Swaggeroauth2TokenParameters model constructor.
     * @property {module:model/Swaggeroauth2TokenParameters}
     */
    Swaggeroauth2TokenParameters,

    /**
     * The Swaggeroauth2TokenResponse model constructor.
     * @property {module:model/Swaggeroauth2TokenResponse}
     */
    Swaggeroauth2TokenResponse,

    /**
     * The SwaggeruserinfoResponsePayload model constructor.
     * @property {module:model/SwaggeruserinfoResponsePayload}
     */
    SwaggeruserinfoResponsePayload,

    /**
     * The UserinfoResponse model constructor.
     * @property {module:model/UserinfoResponse}
     */
    UserinfoResponse,

    /**
     * The Version model constructor.
     * @property {module:model/Version}
     */
    Version,

    /**
     * The WellKnown model constructor.
     * @property {module:model/WellKnown}
     */
    WellKnown,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The PublicApi service constructor.
    * @property {module:api/PublicApi}
    */
    PublicApi,

    /**
    * The VersionApi service constructor.
    * @property {module:api/VersionApi}
    */
    VersionApi
};
